#!/usr/bin/env sh
# Lint all commits that are about to be pushed
upstream=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
if [ -z "$upstream" ]; then
  upstream="origin/main"
fi
npx commitlint --from "$upstream" --to HEAD --verbose
